version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - app-network

  api:
    build: ./api
    ports:
      - "8000:8000"
    env_file:
      - ./api/.env
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/flashcards
    depends_on:
      - db
    networks:
      - app-network

  bot:
    build: ./bot
    env_file:
      - ./bot/.env
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - API_URL=http://api:8000
    depends_on:
      - api
    networks:
      - app-network

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=flashcards
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: